#!/usr/bin/env python3
"""
Idempotent nobu setup. Agents: run this after cloning — no questions needed.

Usage:
  python scripts/bootstrap.py
  python scripts/bootstrap.py --json
  python scripts/bootstrap.py --integrate /path/to/your/game

What it does:
  1. Checks Python >= 3.10
  2. Ensures assets/midi, assets/soundfonts, output/audio exist
  3. Creates .venv if missing
  4. pip install -r requirements.txt into that venv
  5. Verifies imports (fastmcp, midiutil, mido, numpy, soundfile)
  6. Prints MCP config snippet with absolute paths
  7. With --integrate: merges "nobu" into that project's .cursor/mcp.json
     (and legacy .mcp.json for Claude Desktop / older clients)
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MIN_PY = (3, 10)
REQUIRED_PKGS = ("fastmcp", "midiutil", "mido", "numpy", "soundfile")
DIRS = (
    REPO_ROOT / "assets" / "midi",
    REPO_ROOT / "assets" / "soundfonts",
    REPO_ROOT / "output" / "audio",
)


def venv_python() -> Path:
    if platform.system() == "Windows":
        return REPO_ROOT / ".venv" / "Scripts" / "python.exe"
    return REPO_ROOT / ".venv" / "bin" / "python"


def venv_pip() -> list[str]:
    return [str(venv_python()), "-m", "pip"]


def ensure_python_version() -> None:
    if sys.version_info < MIN_PY:
        raise SystemExit(
            f"Python {MIN_PY[0]}.{MIN_PY[1]}+ required; "
            f"found {sys.version_info.major}.{sys.version_info.minor}"
        )


def ensure_dirs() -> list[str]:
    created = []
    for d in DIRS:
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            created.append(str(d))
    return created


def ensure_venv() -> bool:
    py = venv_python()
    if py.exists():
        return False
    subprocess.run(
        [sys.executable, "-m", "venv", str(REPO_ROOT / ".venv")],
        check=True,
    )
    return True


def pip_install() -> None:
    subprocess.run(
        [*venv_pip(), "install", "--upgrade", "pip"],
        check=True,
        cwd=str(REPO_ROOT),
    )
    subprocess.run(
        [*venv_pip(), "install", "-r", str(REPO_ROOT / "requirements.txt")],
        check=True,
        cwd=str(REPO_ROOT),
    )


def verify_imports() -> dict[str, bool]:
    results = {}
    py = str(venv_python())
    for pkg in REQUIRED_PKGS:
        r = subprocess.run(
            [py, "-c", f"import {pkg}"],
            capture_output=True,
            text=True,
        )
        results[pkg] = r.returncode == 0
    r = subprocess.run(
        [py, "-c", "import nobu_mcp; print(nobu_mcp.mcp.name)"],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )
    results["nobu_mcp"] = r.returncode == 0 and "nobu" in (r.stdout or "")
    return results


def mcp_server_entry() -> dict:
    """Cursor / Claude Desktop shape: command + args."""
    py = venv_python()
    server = REPO_ROOT / "nobu_mcp.py"
    return {
        "command": str(py.resolve()),
        "args": [str(server.resolve())],
    }


def kilo_mcp_entry() -> dict:
    """Kilo Code v7+ shape: type local + command array."""
    py = venv_python()
    server = REPO_ROOT / "nobu_mcp.py"
    return {
        "type": "local",
        "command": [str(py.resolve()), str(server.resolve())],
        "enabled": True,
        "timeout": 30000,
    }


def mcp_config_snippet() -> dict:
    return {"mcpServers": {"nobu": mcp_server_entry()}}


def kilo_config_snippet() -> dict:
    return {
        "instructions": [
            "AGENTS.md",
            "CLAUDE.md",
            ".claude/skills/game-music-producer/SKILL.md",
            ".kilo/rules/nobu.md",
        ],
        "mcp": {"nobu": kilo_mcp_entry()},
    }


def write_kilo_config() -> Path:
    """Rewrite .kilo/kilo.jsonc with absolute venv paths for this machine."""
    kilo_dir = REPO_ROOT / ".kilo"
    kilo_dir.mkdir(parents=True, exist_ok=True)
    path = kilo_dir / "kilo.jsonc"
    body = json.dumps(kilo_config_snippet(), indent=2, ensure_ascii=False)
    path.write_text(
        "// Generated by scripts/bootstrap.py (venv absolute paths).\n"
        "// Gitignored — portable template: .kilo/kilo.example.jsonc\n"
        "// Same for .mcp.json / .cursor/mcp.json (.mcp.example.json).\n"
        + body
        + "\n",
        encoding="utf-8",
    )
    return path


def _write_cursor_mcp(mcp_path: Path, entry: dict) -> None:
    """Merge nobu into a Cursor mcp.json (create or update). Project-scoped only."""
    data: dict = {"mcpServers": {}}
    if mcp_path.exists():
        try:
            data = json.loads(mcp_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            raise SystemExit(f"Invalid JSON in {mcp_path}: {e}") from e
        data.setdefault("mcpServers", {})
    data["mcpServers"]["nobu"] = entry
    mcp_path.parent.mkdir(parents=True, exist_ok=True)
    mcp_path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def integrate_mcp(target_dir: Path) -> list[str]:
    """Merge nobu into target project's Cursor + Kilo configs (never global)."""
    target_dir = target_dir.resolve()
    if not target_dir.is_dir():
        raise SystemExit(f"Not a directory: {target_dir}")

    written: list[str] = []
    entry = mcp_server_entry()

    # Cursor project scope: .cursor/mcp.json (current) + legacy root .mcp.json
    for mcp_path in (
        target_dir / ".cursor" / "mcp.json",
        target_dir / ".mcp.json",
    ):
        _write_cursor_mcp(mcp_path, entry)
        written.append(str(mcp_path))

    # Kilo Code v7+
    kilo_dir = target_dir / ".kilo"
    kilo_dir.mkdir(parents=True, exist_ok=True)
    kilo_path = kilo_dir / "kilo.jsonc"
    kilo_data: dict = {}
    if kilo_path.exists():
        raw = kilo_path.read_text(encoding="utf-8")
        # Strip // line comments for parse
        stripped = "\n".join(
            ln
            for ln in raw.splitlines()
            if not ln.strip().startswith("//")
        )
        try:
            kilo_data = json.loads(stripped) if stripped.strip() else {}
        except json.JSONDecodeError as e:
            raise SystemExit(f"Invalid JSONC in {kilo_path}: {e}") from e
    kilo_data.setdefault("mcp", {})
    kilo_data["mcp"]["nobu"] = kilo_mcp_entry()
    instr = kilo_data.setdefault("instructions", [])
    for item in (
        "AGENTS.md",
        ".claude/skills/game-music-producer/SKILL.md",
        ".kilo/rules/nobu.md",
    ):
        # Only add if paths make sense relative to target; skip AGENTS if absent
        if item not in instr:
            if item == "AGENTS.md" and not (target_dir / "AGENTS.md").exists():
                continue
            if item.startswith(".claude/") and not (
                target_dir / ".claude/skills/game-music-producer/SKILL.md"
            ).exists():
                # Point at nobu repo skill via absolute note — keep relative to nobu
                continue
            instr.append(item)
    kilo_path.write_text(
        "// Merged by nobu scripts/bootstrap.py --integrate\n"
        + json.dumps(kilo_data, indent=2, ensure_ascii=False)
        + "\n",
        encoding="utf-8",
    )
    written.append(str(kilo_path))
    return written


def print_human(report: dict) -> None:
    print("=== nobu bootstrap ===")
    print(f"Repo:     {report['repo_root']}")
    print(f"Python:   {report['python']}")
    print(f"Venv:     {report['venv_python']}")
    print(f"Created:  {', '.join(report['dirs_created']) or '(none)'}")
    print(f"Venv new: {report['venv_created']}")
    print("Imports:")
    for name, ok in report["imports"].items():
        print(f"  {'OK' if ok else 'FAIL':4} {name}")
    print()
    print("Cursor project MCP (.cursor/mcp.json):")
    print(json.dumps(report["mcp_config"], indent=2))
    if report.get("cursor_mcp_path"):
        print(f"Wrote:    {report['cursor_mcp_path']}")
    if report.get("kilo_config"):
        print("\nKilo Code (.kilo/kilo.jsonc):")
        print(json.dumps(report["kilo_config"], indent=2))
    if report.get("kilo_config_path"):
        print(f"\nWrote: {report['kilo_config_path']}")
    if report.get("integrated_mcp"):
        print(f"\nIntegrated into: {report['integrated_mcp']}")
    print()
    if all(report["imports"].values()):
        print("Status: READY — reload window, then enable nobu if Cursor shows it disabled.")
        print("Cursor: Settings → MCP → toggle nobu ON (one-time; project .cursor/mcp.json only).")
        print("Skill:  .claude/skills/game-music-producer/")
        print("Kilo:   .kilo/kilo.jsonc + .kilo/rules/nobu.md")
        print("Compose: ask the agent for a track, or: python examples/demo_biome_ost.py")
    else:
        print("Status: INCOMPLETE — fix failed imports and re-run bootstrap.")
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description="Bootstrap nobu for agent/human use")
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON report only",
    )
    parser.add_argument(
        "--integrate",
        metavar="DIR",
        help="Merge nobu MCP entry into DIR/.mcp.json (absolute venv + script paths)",
    )
    parser.add_argument(
        "--skip-install",
        action="store_true",
        help="Only create dirs / print MCP config (no pip)",
    )
    args = parser.parse_args()

    ensure_python_version()
    dirs_created = ensure_dirs()
    venv_created = False
    if not args.skip_install:
        venv_created = ensure_venv()
        pip_install()
        imports = verify_imports()
    else:
        imports = {p: False for p in REQUIRED_PKGS}
        imports["nobu_mcp"] = (REPO_ROOT / "nobu_mcp.py").exists()

    integrated = None
    if args.integrate:
        integrated = integrate_mcp(Path(args.integrate))

    kilo_cfg = None
    cursor_mcp_path = None
    # Project-local Cursor + Kilo configs only (never ~/.cursor/mcp.json)
    if venv_python().exists():
        snippet = json.dumps(mcp_config_snippet(), indent=2) + "\n"
        (REPO_ROOT / ".mcp.json").write_text(snippet, encoding="utf-8")
        cursor_mcp = REPO_ROOT / ".cursor" / "mcp.json"
        cursor_mcp.parent.mkdir(parents=True, exist_ok=True)
        cursor_mcp.write_text(snippet, encoding="utf-8")
        cursor_mcp_path = str(cursor_mcp)
        kilo_cfg = str(write_kilo_config())

    report = {
        "ok": all(imports.values()) if not args.skip_install else True,
        "repo_root": str(REPO_ROOT),
        "python": sys.version.split()[0],
        "venv_python": str(venv_python()),
        "venv_created": venv_created,
        "dirs_created": dirs_created,
        "imports": imports,
        "mcp_config": mcp_config_snippet(),
        "cursor_mcp_path": cursor_mcp_path,
        "kilo_config": kilo_config_snippet() if venv_python().exists() else None,
        "kilo_config_path": kilo_cfg,
        "skill_path": str(
            REPO_ROOT / ".claude" / "skills" / "game-music-producer"
        ),
        "integrated_mcp": integrated,
        "next_steps": [
            "Reload Window (project .cursor/mcp.json — never global ~/.cursor/mcp.json)",
            "Cursor: enable 'nobu' once under Settings → MCP if it appears disabled (Cursor default)",
            "Kilo: Settings → Agent Behaviour → MCP Servers (uses .kilo/kilo.jsonc)",
            "Confirm server 'nobu' exposes: start_project, suggest_scale_for_mood, add_layer, export_midi",
            "Read .claude/skills/game-music-producer/SKILL.md when composing",
            "Optional demo: python examples/demo_biome_ost.py && python scripts/render_midi.py",
        ],
    }

    if args.json:
        print(json.dumps(report, indent=2))
        if not report["ok"]:
            sys.exit(1)
    else:
        print_human(report)


if __name__ == "__main__":
    main()
